services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: fastapi
    ports:
      - '8000:80'
    volumes:
      - ./src:/app/src:z
    depends_on:
      #rabbit:
      #condition: service_healthy
      redis:
        condition: service_started
    restart: 'no'

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - '6379:6379'
    hostname: redis
    environment:
      - REDIS_PASSWORD=redis
    command: ['redis-server', '--loglevel', 'verbose', '--requirepass', 'redis']
    restart: on-failure

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.rq-dashboard
    container_name: rq-dashboard
    ports:
      - '9181:9181'
    environment:
      - RQ_DASHBOARD_REDIS_URL=redis://:redis@redis:6379
    depends_on:
      - redis

  rq-worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: rq-worker
    command: rq worker --url redis://default:redis@redis:6379/0 task_queue
    #volumes:
    #  - ./src:/app/src:z
    depends_on:
      - redis
    restart: 'on-failure'
