services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: fastapi
    ports:
      - '8000:80'
    volumes:
      - ./src:/app/src:z
    depends_on:
      #rabbit:
      #condition: service_healthy
      redis:
        condition: service_started
    restart: 'no'

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - '6379:6379'
    hostname: redis
    environment:
      - REDIS_PASSWORD=redis
    command: ['redis-server', '--loglevel', 'verbose', '--requirepass', 'redis']
    #healthcheck:
    # test: ['CMD', 'redis-cli', '-a', 'redis', client list']
    # interval: 10s
    # timeout: 5s
    # retries: 5
    restart: on-failure
